version: 2.1

jobs:
  lint:
    working_directory: ~/rl-loadout-lib
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies and build
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  build:
    working_directory: ~/rl-loadout-lib
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies and build
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/rl-loadout-lib
          paths: .
  test:
    working_directory: ~/rl-loadout-lib
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies and build
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run mocha tests
          command: npm run test
  deploy:
    working_directory: ~/rl-loadout-lib
    docker:
        - image: circleci/node:10.16
    steps:
      - attach_workspace:
          at: ~/rl-loadout-lib
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/rl-loadout-lib/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - test:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
