export const BODY_GREY_CAR_ID = 597; // DeLorean Time Machine
export const BODY_DARK_CAR_ID = 803; // '16 Batmobile
export const BODY_BERRY_ID = 2665; // The Dark Knight Rises Tumbler
export const BODY_EGGPLANT_ID = 2666; // '89 Batmobile
export const BODY_MAPLE_ID = 2919; // Jurassic Jeep® Wrangler
export const BODY_RYE_TIER1 = 3155; // Maverick
export const BODY_RYE_TIER2 = 3156; // Maverick G1
export const BODY_RYE_TIER3 = 3157; // Maverick GXT
export const BODY_FELINE_ID = 4014; // K.I.T.T.
export const BODY_SLIME_ID = 4155; // Ecto-1
